export function buildRlmFacetWorkerSource(): string {
  return [
    'import { DurableObject, WorkerEntrypoint } from "cloudflare:workers";',
    "",
    "function nowIso() {",
    "  return new Date().toISOString();",
    "}",
    "",
    "function isRecord(value) {",
    '  return typeof value === "object" && value !== null;',
    "}",
    "",
    "function cloneValue(value) {",
    '  if (typeof structuredClone === "function") {',
    "    return structuredClone(value);",
    "  }",
    "  return JSON.parse(JSON.stringify(value));",
    "}",
    "",
    "function safeClone(value) {",
    "  try {",
    '    return typeof structuredClone === "function" ? structuredClone(value) : JSON.parse(JSON.stringify(value));',
    "  } catch {",
    "    return undefined;",
    "  }",
    "}",
    "",
    "function describeRuntimeValue(name, value) {",
    "  const type = value === null ? 'null' : Array.isArray(value) ? 'array' : typeof value;",
    "  const entry = { name, type };",
    "  if (value != null && typeof value === 'object') {",
    "    const ctor = value.constructor?.name;",
    "    if (ctor != null && ctor !== 'Object' && ctor !== 'Array') entry.ctor = ctor;",
    "  }",
    "  if (typeof value === 'string') {",
    "    entry.size = `${value.length} chars`;",
    "    entry.preview = value.length > 120 ? `${value.slice(0, 117)}...` : value;",
    "  } else if (Array.isArray(value)) {",
    "    entry.size = `${value.length} items`;",
    "    entry.preview = JSON.stringify(value.slice(0, 3));",
    "  } else if (value != null && typeof value === 'object') {",
    "    const keys = Object.keys(value);",
    "    entry.size = `${keys.length} keys`;",
    "    entry.preview = keys.slice(0, 8).join(', ');",
    "  } else if (value !== undefined) {",
    "    entry.preview = String(value);",
    "  }",
    "  return entry;",
    "}",
    "",
    "function formatRuntimeState(state) {",
    "  const globals = state?.globals ?? {};",
    "  const entries = Object.keys(globals)",
    "    .sort((left, right) => left.localeCompare(right))",
    "    .map((name) => describeRuntimeValue(name, globals[name]));",
    "  const definitions = Object.keys(state?.definitionStatements ?? {}).sort((left, right) => left.localeCompare(right));",
    "  if (entries.length === 0 && definitions.length === 0) return 'No persisted runtime values yet.';",
    "  return [",
    "    ...entries.map((entry) => {",
    "      const details = [entry.type, entry.ctor, entry.size].filter(Boolean).join(', ');",
    "      return `- ${entry.name}: ${details}${entry.preview != null ? `; preview=${entry.preview}` : ''}`;",
    "    }),",
    "    ...definitions.map((name) => `- ${name}: function/class definition persisted as source`),",
    "  ].join('\\n');",
    "}",
    "",
    "function sanitizeToolName(name) {",
    "  const sanitized = name",
    '    .replace(/[-.\\s]+/g, "_")',
    '    .replace(/[^a-zA-Z0-9_$]/g, "")',
    '    .replace(/^[0-9]/, "_$&");',
    '  return sanitized.length > 0 ? sanitized : "tool";',
    "}",
    "",
    "function isValidJsIdentifier(value) {",
    '  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);',
    "}",
    "",
    "function buildInlineInputAliases(input) {",
    "  const reserved = new Set([",
    '    "SUBMIT",',
    '    "console",',
    '    "corpus",',
    '    "inputs",',
    '    "print",',
    '    "resources",',
    '    "rlm",',
    '    "tools",',
    "  ]);",
    "  return Object.keys(input)",
    "    .filter((key) => isValidJsIdentifier(key) && !reserved.has(key))",
    "    .sort((left, right) => left.localeCompare(right))",
    "    .map((key) => ({ key, variableName: key }));",
    "}",
    "",
    "function pathMatchForCorpus(path) {",
    '  const match = /^\\/corpora\\/([^/]+)\\/(.+)$/.exec(path);',
    "  if (match == null) {",
    "    return null;",
    "  }",
    "  return { corpusId: decodeURIComponent(match[1]), relativePath: match[2] };",
    "}",
    "",
    "function readTextSlice(text, options, fallbackMaxChars) {",
    "  const startChar = Math.max(0, Math.min(text.length, options.startChar ?? 0));",
    "  const maxChars = Math.max(1, Math.min(options.maxChars ?? fallbackMaxChars, fallbackMaxChars));",
    "  const endChar = Math.min(text.length, startChar + maxChars);",
    "  return {",
    "    startChar,",
    "    endChar,",
    "    totalChars: text.length,",
    "    truncated: endChar < text.length,",
    "    text: text.slice(startChar, endChar),",
    "  };",
    "}",
    "",
    "function searchWithinText(path, text, query, options) {",
    "  const haystack = options.caseSensitive ? text : text.toLowerCase();",
    "  const needle = options.caseSensitive ? query : query.toLowerCase();",
    "  const maxResults = Math.max(1, options.maxResults ?? 5);",
    "  const contextChars = Math.max(0, options.contextChars ?? 80);",
    "  const matches = [];",
    "  if (needle.length === 0) {",
    "    return { path, query, matches, truncated: false };",
    "  }",
    "  let cursor = 0;",
    "  while (matches.length < maxResults) {",
    "    const index = haystack.indexOf(needle, cursor);",
    "    if (index < 0) {",
    "      break;",
    "    }",
    "    const startChar = index;",
    "    const endChar = index + needle.length;",
    "    const snippetStart = Math.max(0, startChar - contextChars);",
    "    const snippetEnd = Math.min(text.length, endChar + contextChars);",
    "    matches.push({",
    "      path,",
    "      startChar,",
    "      endChar,",
    "      match: text.slice(startChar, endChar),",
    "      snippet: text.slice(snippetStart, snippetEnd),",
    "    });",
    "    cursor = endChar;",
    "  }",
    "  return { path, query, matches, truncated: false };",
    "}",
    "",
    "function hasExternalContext(context) {",
    "  const manifest = isRecord(context?.manifest) ? context.manifest : {};",
    "  const corpora = Array.isArray(manifest.corpora) ? manifest.corpora : [];",
    "  return (context?.resources?.length ?? 0) > 0 || corpora.length > 0;",
    "}",
    "",
    "function buildStepRunnerSource(state, stepArgs) {",
    "  const definitionPrelude = Object.entries(state.definitionStatements ?? {})",
    "    .sort(([left], [right]) => left.localeCompare(right))",
    "    .map(([name, statement]) => `if (${name} === undefined) { ${statement} }`)",
    "    .join('\\n');",
    "  const trackedPrelude = (stepArgs.compiled.trackedNames ?? [])",
    "    .map((name) => `let ${name} = safeClone(SNAPSHOT.globals[${JSON.stringify(name)}]);`)",
    "    .join('\\n');",
    "  const trackedSync = (stepArgs.compiled.trackedNames ?? [])",
    "    .map((name) => `__syncGlobal(__globals, ${JSON.stringify(name)}, ${name});`)",
    "    .join('\\n');",
    "  const inlineAliases = buildInlineInputAliases(state.inlineInputs ?? {})",
    "    .map(({ key, variableName }) => `const ${variableName} = inputs[${JSON.stringify(key)}];`)",
    "    .join('\\n');",
    "  const toolAliases = (state.tools ?? [])",
    "    .map((tool) => {",
    "      const alias = sanitizeToolName(tool.name);",
    "      return `const ${alias} = async (args = {}) => __callTool(${JSON.stringify(tool.name)}, args, async () => { const response = await __hostFetch(\"/execute-tool\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, toolName: ${JSON.stringify(tool.name)}, input: args }); return response.output; });`;",
    "    })",
    "    .join('\\n');",
    "  const toolObject = (state.tools ?? [])",
    "    .map((tool) => {",
    "      const alias = sanitizeToolName(tool.name);",
    "      return `${JSON.stringify(alias)}: ${alias}`;",
    "    })",
    "    .join(',\\n');",
    "  const snapshot = JSON.stringify({",
    "    runId: state.runId,",
    "    moduleId: state.moduleId,",
    "    preparedContext: state.preparedContext,",
    "    inlineInputs: state.inlineInputs,",
    "    request: stepArgs.request,",
    "  });",
    "  const externalContext = hasExternalContext(state.preparedContext);",
    "  return [",
    "    'import { WorkerEntrypoint } from \"cloudflare:workers\";',",
    "    'const SNAPSHOT_META = ' + snapshot + ';',",
    "    readTextSlice.toString(),",
    "    searchWithinText.toString(),",
    "    pathMatchForCorpus.toString(),",
    "    safeClone.toString(),",
    "    describeRuntimeValue.toString(),",
    "    'function nowIso() { return new Date().toISOString(); }',",
    "    'function isRecord(value) { return typeof value === \"object\" && value !== null; }',",
    "    'function __formatValue(value) { if (typeof value === \"string\") return value; try { return JSON.stringify(value); } catch { return String(value); } }',",
    "    'function __syncGlobal(target, key, value) { const cloned = safeClone(value); if (cloned === undefined && value !== undefined) { delete target[key]; return; } target[key] = cloned; }',",
    "    'export class RlmStepRunner extends WorkerEntrypoint {',",
    "    '  async run() {',",
    "    '    const __globals = cloneValue(SNAPSHOT.globals ?? {});',",
    "    '    let __submitted;',",
    "    '    let __queryCallsUsed = SNAPSHOT.request.queryCallsUsed;',",
    "    '    const __logs = [];',",
    "    '    const __toolCalls = [];',",
    "    '    const __pendingTasks = new Set();',",
    "    '    let __stepError;',",
    "    '    const inputs = SNAPSHOT.inlineInputs ?? {};',",
    "    '    const SUBMIT = async (value) => { __submitted = value; return value; };',",
    "    '    const print = (...args) => { __logs.push(args.map(__formatValue).join(\" \")); };',",
    "    '    const inspect_runtime = () => Object.freeze(JSON.parse(JSON.stringify(Object.keys(__globals).sort((left, right) => left.localeCompare(right)).map((name) => describeRuntimeValue(name, __globals[name])))));',",
    "    '    const console = { log: (...args) => print(...args), warn: (...args) => print(...args), error: (...args) => print(...args) };',",
    "    '    const __hostFetch = async (path, payload) => { const response = await fetch(`https://runtime.local${path}`, { method: \"POST\", headers: { \"content-type\": \"application/json\" }, body: JSON.stringify(payload) }); if (!response.ok) { throw new Error(await response.text()); } return response.json(); };',",
    "    '    const __runtimeState = await __hostFetch(\"/step-runtime-state\", { runId: SNAPSHOT_META.runId, moduleId: SNAPSHOT_META.moduleId });',",
    "    '    const SNAPSHOT = { ...SNAPSHOT_META, globals: __runtimeState.globals ?? {} };',",
    "    '    const __readTextResource = async (path) => { const prepared = SNAPSHOT.preparedContext ?? {}; if (path === prepared.manifestPath || (prepared.resources ?? []).some((resource) => resource.path === path)) { const response = await __hostFetch(\"/read-prepared-text\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path }); const text = response.content; return { path, storage: \"prepared\", text, totalChars: text.length, preview: text.slice(0, 240) }; } const corpusMatch = pathMatchForCorpus(path); if (corpusMatch != null) { const response = await __hostFetch(\"/read-corpus-file\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId: corpusMatch.corpusId, path: corpusMatch.relativePath }); const text = response.content; return { path, storage: \"corpus\", text, totalChars: text.length, preview: text.slice(0, 240) }; } throw new Error(`Unknown prepared text path: ${path}`); };',",
    "    '    const __callTool = (toolName, input, fn) => { const startedAt = nowIso(); const task = (async () => { try { const output = await fn(); __toolCalls.push({ toolName, input, output, source: \"rlm\", startedAt, endedAt: nowIso() }); return output; } catch (error) { const serialized = { message: error instanceof Error ? error.message : String(error) }; __toolCalls.push({ toolName, input, error: serialized, source: \"rlm\", startedAt, endedAt: nowIso() }); throw error; } finally { __pendingTasks.delete(task); } })(); __pendingTasks.add(task); return task; };',",
    "    '    const rlm = {',",
    "    '      query: async (prompt, options) => __callTool(\"rlm.query\", { prompt, options }, async () => { __queryCallsUsed += 1; if (__queryCallsUsed > SNAPSHOT.request.maxQueryCalls) throw new Error(`RLM query budget exceeded: ${__queryCallsUsed} > ${SNAPSHOT.request.maxQueryCalls}.`); const response = await __hostFetch(\"/query\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, prompt, options }); return response.text; }),',",
    "    '      queryBatch: async (prompts, options) => __callTool(\"rlm.queryBatch\", { prompts, options }, async () => { __queryCallsUsed += prompts.length; if (__queryCallsUsed > SNAPSHOT.request.maxQueryCalls) throw new Error(`RLM query budget exceeded: ${__queryCallsUsed} > ${SNAPSHOT.request.maxQueryCalls}.`); const response = await __hostFetch(\"/query-batch\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, prompts, options }); return response.texts; }),',",
    "    '    };',",
    "    '    const state = {',",
    "    '      readText: async (path) => __callTool(\"rlm.state.readText\", { path }, async () => (await __hostFetch(\"/state-read-text\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path })).content),',",
    "    '      readFile: async (path) => state.readText(path),',",
    "    '      writeText: async (path, content) => __callTool(\"rlm.state.writeText\", { path, chars: String(content).length }, async () => __hostFetch(\"/state-write-text\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path, content: String(content) })),',",
    "    '      writeFile: async (path, content) => state.writeText(path, content),',",
    "    '      readJson: async (path) => __callTool(\"rlm.state.readJson\", { path }, async () => (await __hostFetch(\"/state-read-json\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path })).value),',",
    "    '      writeJson: async (path, value) => __callTool(\"rlm.state.writeJson\", { path }, async () => __hostFetch(\"/state-write-json\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path, value })),',",
    "    '      glob: async (pattern) => __callTool(\"rlm.state.glob\", { pattern }, async () => (await __hostFetch(\"/state-glob\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, pattern })).files),',",
    "    '      searchFiles: async (pattern, query, options = {}) => __callTool(\"rlm.state.searchFiles\", { pattern, query, ...options }, async () => (await __hostFetch(\"/state-search-files\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, pattern, query, options })).files),',",
    "    '      mkdir: async (path, options = {}) => __callTool(\"rlm.state.mkdir\", { path, ...options }, async () => __hostFetch(\"/state-mkdir\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path, ...(options ?? {}) })),',",
    "    '      rm: async (path, options = {}) => __callTool(\"rlm.state.rm\", { path, ...options }, async () => __hostFetch(\"/state-rm\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, path, ...(options ?? {}) })),',",
    "    '      info: async () => __callTool(\"rlm.state.info\", {}, async () => __hostFetch(\"/state-info\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId })),',",
    "    '      materializeCorpus: async (corpusId, options = {}) => __callTool(\"rlm.state.materializeCorpus\", { corpusId, ...(options ?? {}) }, async () => __hostFetch(\"/state-materialize-corpus\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, ...(options ?? {}) })),',",
    "    '    };',",
    "    ...(externalContext ? [",
    "      '    const resources = {',",
    "      '      manifest: async () => SNAPSHOT.preparedContext?.manifest ?? null,',",
    "      '      list: async () => SNAPSHOT.preparedContext?.resources ?? [],',",
    "      '      input: async (key) => key == null ? inputs : inputs[key],',",
    "      '      info: async (path) => __callTool(\"rlm.getTextInfo\", { path }, async () => { const resource = await __readTextResource(path); return { path: resource.path, storage: resource.storage, totalChars: resource.totalChars, preview: resource.preview }; }),',",
    "      '      readText: async (path, options = {}) => __callTool(\"rlm.readText\", { path, ...options }, async () => { const resource = await __readTextResource(path); return { path: resource.path, storage: resource.storage, ...readTextSlice(resource.text, options ?? {}, SNAPSHOT.request.maxOutputChars) }; }),',",
    "      '      searchText: async (path, queryText, options = {}) => __callTool(\"rlm.searchText\", { path, query: queryText, ...options }, async () => { const resource = await __readTextResource(path); return { storage: resource.storage, ...searchWithinText(resource.path, resource.text, queryText, options ?? {}) }; }),',",
    "      '      readMatchWindow: async (path, match, options = {}) => __callTool(\"rlm.readMatchWindow\", { path, match, ...options }, async () => { const resource = await __readTextResource(path); const beforeChars = Math.max(0, options.beforeChars ?? 80); const afterChars = Math.max(0, options.afterChars ?? 80); const startChar = Math.max(0, match.startChar - beforeChars); const defaultMaxChars = match.endChar - match.startChar + beforeChars + afterChars; return { path: resource.path, storage: resource.storage, ...readTextSlice(resource.text, { startChar, maxChars: options.maxChars ?? defaultMaxChars }, SNAPSHOT.request.maxOutputChars) }; }),',",
    "      '    };',",
    "      '    const corpus = {',",
    "      '      listFiles: async (corpusId, prefix) => __callTool(\"rlm.listCorpusFiles\", prefix == null ? { corpusId } : { corpusId, prefix }, async () => { const response = await __hostFetch(\"/list-corpus-files\", prefix == null ? { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId } : { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, prefix }); return response.files; }),',",
    "      '      readFile: async (corpusId, path) => __callTool(\"rlm.readCorpusFile\", { corpusId, path }, async () => __hostFetch(\"/read-corpus-file\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, path })),',",
    "      '      search: async (corpusId, args = {}) => __callTool(\"rlm.searchCorpus\", { corpusId, ...(args ?? {}) }, async () => __hostFetch(\"/search-corpus\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, ...(args ?? {}) })),',",
    "      '    };',",
    "    ] : []),",
    "    trackedPrelude,",
    '    "    " + definitionPrelude,',
    "    inlineAliases,",
    "    toolAliases,",
    "    '    const tools = {',",
    "    toolObject.length > 0 ? `    ${toolObject}` : '',",
    "    '    };',",
    "    '    try {',",
    '    "      " + stepArgs.compiled.transformedCode.replace(/\\n/g, "\\n      "),',
    "    '    } catch (error) {',",
    "    '      __stepError = error instanceof Error ? error.message : String(error);',",
    "    '    } finally {',",
    "    '      if (__pendingTasks.size > 0) {',",
    "    '        const settled = await Promise.allSettled([...__pendingTasks]);',",
    "    '        const rejected = settled.find((entry) => entry.status === \"rejected\");',",
    "    '        if (__stepError == null && rejected != null) __stepError = rejected.reason instanceof Error ? rejected.reason.message : String(rejected.reason);',",
    "    '      }',",
    "    '    }',",
    "    trackedSync,",
    "    '    return { submitted: __submitted, queryCallsUsed: __queryCallsUsed, logs: __logs, stdout: __logs.length > 0 ? __logs.join(\"\\\\n\") : undefined, toolCalls: __toolCalls, globals: __globals, error: __stepError };',",
    "    '  }',",
    "    '}',",
    "    cloneValue.toString(),",
    "].join('\\n');",
    "}",
    "",
    "export class RlmSessionFacet extends DurableObject {",
    "  constructor(ctx, env) {",
    "    super(ctx, env);",
    "    this.ctx = ctx;",
    "    this.env = env;",
    "    this.state = null;",
    "    this.ctx.blockConcurrencyWhile(async () => {",
    "      this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS session_state (state_key TEXT PRIMARY KEY, state_json TEXT NOT NULL, updated_at TEXT NOT NULL)`);",
    "      this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS session_step_journal (step_index INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL, result_json TEXT NOT NULL, created_at TEXT NOT NULL)`);",
    "      this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS session_workspace_entries (path TEXT PRIMARY KEY, entry_type TEXT NOT NULL, content_text TEXT, r2_key TEXT, size INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL)`);",
    "    });",
    "  }",
    "",
    "  async __loadJson(key) {",
    "    const rows = this.ctx.storage.sql.exec('SELECT state_json FROM session_state WHERE state_key = ? LIMIT 1', key).toArray();",
    "    return rows[0] == null ? undefined : JSON.parse(rows[0].state_json);",
    "  }",
    "",
    "  async __saveJson(key, value) {",
    "    this.ctx.storage.sql.exec('INSERT OR REPLACE INTO session_state (state_key, state_json, updated_at) VALUES (?, ?, ?)', key, JSON.stringify(value), nowIso());",
    "  }",
    "",
    "  async __loadState() {",
    "    if (this.state != null) {",
    "      return this.state;",
    "    }",
    "    const state = (await this.__loadJson('session')) ?? null;",
    "    this.state = state;",
    "    return state;",
    "  }",
    "",
    "  async __saveState() {",
    "    if (this.state == null) {",
    "      return;",
    "    }",
    "    await this.__saveJson('session', this.state);",
    "  }",
    "",
    "  __workspacePath(path) {",
    "    if (typeof path !== 'string' || path.length === 0) throw new Error('Workspace path must be a non-empty string.');",
    "    const normalized = (path.startsWith('/') ? path : `/${path}`).replace(/\\/{2,}/g, '/');",
    "    if (normalized.includes('\\0')) throw new Error('Workspace paths cannot contain null bytes.');",
    "    return normalized;",
    "  }",
    "",
    "  __workspaceBucket() {",
    "    return this.env.SO_RLM_WORKSPACE ?? this.env.SO_ARTIFACTS ?? null;",
    "  }",
    "",
    "  __workspaceR2Key(path) {",
    "    const state = this.state ?? {};",
    "    const runId = String(state.runId ?? 'unknown').replace(/[^a-zA-Z0-9._-]+/g, '_');",
    "    return `rlm-workspaces/${runId}${path}`;",
    "  }",
    "",
    "  __globToRegExp(pattern) {",
    "    const normalized = this.__workspacePath(pattern);",
    "    let source = '^';",
    "    for (let index = 0; index < normalized.length; index += 1) {",
    "      const char = normalized[index];",
    "      const next = normalized[index + 1];",
    "      if (char === '*' && next === '*') { source += '.*'; index += 1; continue; }",
    "      if (char === '*') { source += '[^/]*'; continue; }",
    "      if (char === '?') { source += '[^/]'; continue; }",
    "      source += char.replace(/[|\\\\{}()[\\]^$+?.]/g, '\\\\$&');",
    "    }",
    "    return new RegExp(`${source}$`);",
    "  }",
    "",
    "  async __workspaceReadText(path) {",
    "    const normalized = this.__workspacePath(path);",
    "    const rows = this.ctx.storage.sql.exec('SELECT content_text, r2_key FROM session_workspace_entries WHERE path = ? AND entry_type = ? LIMIT 1', normalized, 'file').toArray();",
    "    const row = rows[0];",
    "    if (row == null) throw new Error(`Workspace file \"${normalized}\" was not found.`);",
    "    if (row.r2_key != null) {",
    "      const bucket = this.__workspaceBucket();",
    "      if (bucket == null) throw new Error('Workspace file is R2-backed, but no workspace R2 bucket is bound.');",
    "      const object = await bucket.get(row.r2_key);",
    "      if (object == null) throw new Error(`Workspace R2 object \"${row.r2_key}\" was not found.`);",
    "      return object.text();",
    "    }",
    "    return row.content_text ?? '';",
    "  }",
    "",
    "  async __workspaceWriteText(path, content) {",
    "    const normalized = this.__workspacePath(path);",
    "    const text = String(content);",
    "    const size = new TextEncoder().encode(text).byteLength;",
    "    const bucket = this.__workspaceBucket();",
    "    let contentText = text;",
    "    let r2Key = null;",
    "    if (bucket != null && size > 1500000) {",
    "      r2Key = this.__workspaceR2Key(normalized);",
    "      await bucket.put(r2Key, text);",
    "      contentText = null;",
    "    }",
    "    this.ctx.storage.sql.exec('INSERT OR REPLACE INTO session_workspace_entries (path, entry_type, content_text, r2_key, size, updated_at) VALUES (?, ?, ?, ?, ?, ?)', normalized, 'file', contentText, r2Key, size, nowIso());",
    "    const directory = normalized.split('/').slice(0, -1).join('/') || '/';",
    "    if (directory !== normalized) await this.stateMkdir({ path: directory, recursive: true });",
    "    return { path: normalized, bytes: size };",
    "  }",
    "",
    "  async stateWriteExternalText(args) {",
    "    const normalized = this.__workspacePath(args.path);",
    "    const size = Math.max(0, Number(args.size) || 0);",
    "    this.ctx.storage.sql.exec('INSERT OR REPLACE INTO session_workspace_entries (path, entry_type, content_text, r2_key, size, updated_at) VALUES (?, ?, ?, ?, ?, ?)', normalized, 'file', null, String(args.r2Key), size, nowIso());",
    "    const directory = normalized.split('/').slice(0, -1).join('/') || '/';",
    "    if (directory !== normalized) await this.stateMkdir({ path: directory, recursive: true });",
    "    return { path: normalized, bytes: size, r2Key: String(args.r2Key) };",
    "  }",
    "",
    "  async stateMkdir(args) {",
    "    const normalized = this.__workspacePath(args.path);",
    "    const parts = normalized.split('/').filter(Boolean);",
    "    const paths = args.recursive === false ? [normalized] : ['/', ...parts.map((_, index) => `/${parts.slice(0, index + 1).join('/')}`)];",
    "    for (const path of paths) {",
    "      this.ctx.storage.sql.exec('INSERT OR IGNORE INTO session_workspace_entries (path, entry_type, size, updated_at) VALUES (?, ?, ?, ?)', path, 'directory', 0, nowIso());",
    "    }",
    "    return { path: normalized, r2Keys: rows.map((row) => row.r2_key).filter((key) => key != null) };",
    "  }",
    "",
    "  async stateRm(args) {",
    "    const normalized = this.__workspacePath(args.path);",
    "    const prefix = `${normalized.replace(/\\/$/, '')}/%`;",
    "    const rows = args.recursive === false",
    "      ? this.ctx.storage.sql.exec('SELECT path, r2_key FROM session_workspace_entries WHERE path = ?', normalized).toArray()",
    "      : this.ctx.storage.sql.exec('SELECT path, r2_key FROM session_workspace_entries WHERE path = ? OR path LIKE ?', normalized, prefix).toArray();",
    "    if (rows.length === 0 && args.force !== true) throw new Error(`Workspace path \"${normalized}\" was not found.`);",
    "    const bucket = this.__workspaceBucket();",
    "    for (const row of rows) {",
    "      if (bucket != null && row.r2_key != null) await bucket.delete(row.r2_key).catch(() => undefined);",
    "    }",
    "    if (args.recursive === false) {",
    "      this.ctx.storage.sql.exec('DELETE FROM session_workspace_entries WHERE path = ?', normalized);",
    "    } else {",
    "      this.ctx.storage.sql.exec('DELETE FROM session_workspace_entries WHERE path = ? OR path LIKE ?', normalized, prefix);",
    "    }",
    "    return { path: normalized };",
    "  }",
    "",
    "  async stateReadText(args) {",
    "    const path = this.__workspacePath(args.path);",
    "    return { path, content: await this.__workspaceReadText(path) };",
    "  }",
    "",
    "  async stateWriteText(args) {",
    "    return this.__workspaceWriteText(args.path, args.content);",
    "  }",
    "",
    "  async stateReadJson(args) {",
    "    const path = this.__workspacePath(args.path);",
    "    return { path, value: JSON.parse(await this.__workspaceReadText(path)) };",
    "  }",
    "",
    "  async stateWriteJson(args) {",
    "    return this.__workspaceWriteText(args.path, JSON.stringify(args.value, null, 2));",
    "  }",
    "",
    "  async stateGlob(args) {",
    "    const pattern = this.__workspacePath(args.pattern);",
    "    const regex = this.__globToRegExp(pattern);",
    "    const rows = this.ctx.storage.sql.exec('SELECT path FROM session_workspace_entries WHERE entry_type = ? ORDER BY path', 'file').toArray();",
    "    return { pattern, files: rows.map((row) => row.path).filter((path) => regex.test(path)) };",
    "  }",
    "",
    "  async stateSearchFiles(args) {",
    "    const glob = await this.stateGlob({ pattern: args.pattern });",
    "    const options = args.options ?? {};",
    "    const query = String(args.query ?? '');",
    "    const files = [];",
    "    for (const path of glob.files) {",
    "      const text = await this.__workspaceReadText(path);",
    "      const haystack = options.caseSensitive ? text : text.toLowerCase();",
    "      const needle = options.caseSensitive ? query : query.toLowerCase();",
    "      const maxResults = Math.max(1, options.maxResults ?? 5);",
    "      const contextChars = Math.max(0, options.contextChars ?? 80);",
    "      const matches = [];",
    "      if (needle.length > 0) {",
    "        let cursor = 0;",
    "        while (matches.length < maxResults) {",
    "          const index = haystack.indexOf(needle, cursor);",
    "          if (index < 0) break;",
    "          const startChar = index;",
    "          const endChar = index + needle.length;",
    "          matches.push({ startChar, endChar, match: text.slice(startChar, endChar), snippet: text.slice(Math.max(0, startChar - contextChars), Math.min(text.length, endChar + contextChars)) });",
    "          cursor = endChar;",
    "        }",
    "      }",
    "      if (matches.length > 0) files.push({ path, matches });",
    "    }",
    "    return { pattern: glob.pattern, query, files };",
    "  }",
    "",
    "  async stateInfo() {",
    "    const rows = this.ctx.storage.sql.exec('SELECT entry_type, size, r2_key FROM session_workspace_entries').toArray();",
    "    return {",
    "      fileCount: rows.filter((row) => row.entry_type === 'file').length,",
    "      directoryCount: rows.filter((row) => row.entry_type === 'directory').length,",
    "      totalBytes: rows.reduce((sum, row) => sum + (Number(row.size) || 0), 0),",
    "      r2FileCount: rows.filter((row) => row.entry_type === 'file' && row.r2_key != null).length,",
    "    };",
    "  }",
    "",
    "  async init(args) {",
    "    this.state = {",
    "      runId: args.runId,",
    "      moduleId: args.moduleId,",
    "      preparedContext: args.preparedContext,",
    "      inlineInputs: args.inlineInputs,",
    "      textResources: args.textResources,",
    "      corpusIds: args.corpusIds,",
    "      tools: args.tools,",
    "      globals: {},",
    "      trackedNames: [],",
    "      definitionStatements: {},",
    "      lastUpdatedAt: nowIso(),",
    "    };",
    "    this.ctx.storage.sql.exec('DELETE FROM session_step_journal');",
    "    this.ctx.storage.sql.exec('DELETE FROM session_state WHERE state_key = ?', 'checkpoint');",
    "    await this.__saveState();",
    "    return { ok: true };",
    "  }",
    "",
    "  async describe() {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    "      return { trackedNames: [], runtimeState: 'No persisted runtime values yet.' };",
    "    }",
    "    return { trackedNames: state.trackedNames ?? [], runtimeState: formatRuntimeState(state) };",
    "  }",
    "",
    "  async exportState() {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    '      throw new Error("RLM facet session was not initialized.");',
    "    }",
    "    return cloneValue({",
    "      runId: state.runId,",
    "      moduleId: state.moduleId,",
    "      preparedContext: state.preparedContext,",
    "      inlineInputs: state.inlineInputs,",
    "      textResources: state.textResources ?? {},",
    "      globals: state.globals ?? {},",
    "      definitionStatements: state.definitionStatements ?? {},",
    "      tools: state.tools ?? [],",
    "    });",
    "  }",
    "",
    "  async applyStepResult(args) {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    '      throw new Error("RLM facet session was not initialized.");',
    "    }",
    "    const result = args.result ?? {};",
    "    state.globals = isRecord(result.globals) ? result.globals : {};",
    "    state.trackedNames = args.compiled.trackedNames ?? [];",
    "    const definitions = { ...(state.definitionStatements ?? {}) };",
    "    for (const name of args.compiled.declaredNames ?? []) {",
    "      if (Object.prototype.hasOwnProperty.call(state.globals, name)) {",
    "        delete definitions[name];",
    "      }",
    "    }",
    "    for (const entry of args.compiled.definitionStatements ?? []) {",
    "      definitions[entry.name] = entry.statement;",
    "    }",
    "    state.definitionStatements = definitions;",
    "    state.lastUpdatedAt = nowIso();",
    "    await this.__saveState();",
    "    this.ctx.storage.sql.exec('INSERT INTO session_step_journal (code, result_json, created_at) VALUES (?, ?, ?)', args.request.code, JSON.stringify({ logs: result.logs ?? [], submitted: result.submitted, error: result.error ?? null, toolCalls: result.toolCalls ?? [], queryCallsUsed: result.queryCallsUsed ?? args.request.queryCallsUsed }), nowIso());",
    "    return { ok: true };",
    "  }",
    "",
    "  async checkpoint(checkpoint) {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    "      return;",
    "    }",
    "    state.lastUpdatedAt = nowIso();",
    "    await this.__saveJson('checkpoint', checkpoint);",
    "    await this.__saveState();",
    "  }",
    "",
    "  async resume() {",
    "    return (await this.__loadJson('checkpoint')) ?? null;",
    "  }",
    "",
    "  async close() {",
    "    return { ok: true };",
    "  }",
    "}",
  ].join("\n");
}
