export function buildRlmFacetWorkerSource(): string {
  return [
    'import { DurableObject, WorkerEntrypoint } from "cloudflare:workers";',
    "",
    "function nowIso() {",
    "  return new Date().toISOString();",
    "}",
    "",
    "function isRecord(value) {",
    '  return typeof value === "object" && value !== null;',
    "}",
    "",
    "function cloneValue(value) {",
    '  if (typeof structuredClone === "function") {',
    "    return structuredClone(value);",
    "  }",
    "  return JSON.parse(JSON.stringify(value));",
    "}",
    "",
    "function safeClone(value) {",
    "  try {",
    '    return typeof structuredClone === "function" ? structuredClone(value) : JSON.parse(JSON.stringify(value));',
    "  } catch {",
    "    return undefined;",
    "  }",
    "}",
    "",
    "function sanitizeToolName(name) {",
    "  const sanitized = name",
    '    .replace(/[-.\\s]+/g, "_")',
    '    .replace(/[^a-zA-Z0-9_$]/g, "")',
    '    .replace(/^[0-9]/, "_$&");',
    '  return sanitized.length > 0 ? sanitized : "tool";',
    "}",
    "",
    "function isValidJsIdentifier(value) {",
    '  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);',
    "}",
    "",
    "function buildInlineInputAliases(input) {",
    "  const reserved = new Set([",
    '    "SUBMIT",',
    '    "console",',
    '    "getInput",',
    '    "getManifest",',
    '    "inputs",',
    '    "listCorpusFiles",',
    '    "listResources",',
    '    "llm_query",',
    '    "llm_query_batched",',
    '    "print",',
    '    "query",',
    '    "queryBatch",',
    '    "readCorpusFile",',
    '    "readMatchWindow",',
    '    "readText",',
    '    "searchCorpus",',
    '    "searchText",',
    '    "tools",',
    "  ]);",
    "  return Object.keys(input)",
    "    .filter((key) => isValidJsIdentifier(key) && !reserved.has(key))",
    "    .sort((left, right) => left.localeCompare(right))",
    "    .map((key) => ({ key, variableName: key }));",
    "}",
    "",
    "function pathMatchForCorpus(path) {",
    '  const match = /^\\/corpora\\/([^/]+)\\/(.+)$/.exec(path);',
    "  if (match == null) {",
    "    return null;",
    "  }",
    "  return { corpusId: decodeURIComponent(match[1]), relativePath: match[2] };",
    "}",
    "",
    "function readTextSlice(text, options, fallbackMaxChars) {",
    "  const startChar = Math.max(0, Math.min(text.length, options.startChar ?? 0));",
    "  const maxChars = Math.max(1, Math.min(options.maxChars ?? fallbackMaxChars, fallbackMaxChars));",
    "  const endChar = Math.min(text.length, startChar + maxChars);",
    "  return {",
    "    startChar,",
    "    endChar,",
    "    totalChars: text.length,",
    "    truncated: endChar < text.length,",
    "    text: text.slice(startChar, endChar),",
    "  };",
    "}",
    "",
    "function searchWithinText(path, text, query, options) {",
    "  const haystack = options.caseSensitive ? text : text.toLowerCase();",
    "  const needle = options.caseSensitive ? query : query.toLowerCase();",
    "  const maxResults = Math.max(1, options.maxResults ?? 5);",
    "  const contextChars = Math.max(0, options.contextChars ?? 80);",
    "  const matches = [];",
    "  if (needle.length === 0) {",
    "    return { path, query, matches, truncated: false };",
    "  }",
    "  let cursor = 0;",
    "  while (matches.length < maxResults) {",
    "    const index = haystack.indexOf(needle, cursor);",
    "    if (index < 0) {",
    "      break;",
    "    }",
    "    const startChar = index;",
    "    const endChar = index + needle.length;",
    "    const snippetStart = Math.max(0, startChar - contextChars);",
    "    const snippetEnd = Math.min(text.length, endChar + contextChars);",
    "    matches.push({",
    "      path,",
    "      startChar,",
    "      endChar,",
    "      match: text.slice(startChar, endChar),",
    "      snippet: text.slice(snippetStart, snippetEnd),",
    "    });",
    "    cursor = endChar;",
    "  }",
    "  return { path, query, matches, truncated: false };",
    "}",
    "",
    "function buildStepRunnerSource(state, stepArgs) {",
    "  const definitionPrelude = Object.entries(state.definitionStatements ?? {})",
    "    .sort(([left], [right]) => left.localeCompare(right))",
    "    .map(([name, statement]) => `if (${name} === undefined) { ${statement} }`)",
    "    .join('\\n');",
    "  const trackedPrelude = (stepArgs.compiled.trackedNames ?? [])",
    "    .map((name) => `let ${name} = safeClone(SNAPSHOT.globals[${JSON.stringify(name)}]);`)",
    "    .join('\\n');",
    "  const trackedSync = (stepArgs.compiled.trackedNames ?? [])",
    "    .map((name) => `__syncGlobal(__globals, ${JSON.stringify(name)}, ${name});`)",
    "    .join('\\n');",
    "  const inlineAliases = buildInlineInputAliases(state.inlineInputs ?? {})",
    "    .map(({ key, variableName }) => `const ${variableName} = inputs[${JSON.stringify(key)}];`)",
    "    .join('\\n');",
    "  const toolAliases = (state.tools ?? [])",
    "    .map((tool) => {",
    "      const alias = sanitizeToolName(tool.name);",
    "      return `const ${alias} = async (args = {}) => __callTool(${JSON.stringify(tool.name)}, args, async () => { const response = await __hostFetch(\"/execute-tool\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, toolName: ${JSON.stringify(tool.name)}, input: args }); return response.output; });`;",
    "    })",
    "    .join('\\n');",
    "  const toolObject = (state.tools ?? [])",
    "    .map((tool) => {",
    "      const alias = sanitizeToolName(tool.name);",
    "      return `${JSON.stringify(alias)}: ${alias}`;",
    "    })",
    "    .join(',\\n');",
    "  const snapshot = JSON.stringify({",
    "    runId: state.runId,",
    "    moduleId: state.moduleId,",
    "    preparedContext: state.preparedContext,",
    "    inlineInputs: state.inlineInputs,",
    "    textResources: state.textResources,",
    "    globals: state.globals ?? {},",
    "    request: stepArgs.request,",
    "  });",
    "  return [",
    "    'import { WorkerEntrypoint } from \"cloudflare:workers\";',",
    "    'const SNAPSHOT = ' + snapshot + ';',",
    "    readTextSlice.toString(),",
    "    searchWithinText.toString(),",
    "    pathMatchForCorpus.toString(),",
    "    safeClone.toString(),",
    "    'function nowIso() { return new Date().toISOString(); }',",
    "    'function isRecord(value) { return typeof value === \"object\" && value !== null; }',",
    "    'function __formatValue(value) { if (typeof value === \"string\") return value; try { return JSON.stringify(value); } catch { return String(value); } }',",
    "    'function __syncGlobal(target, key, value) { const cloned = safeClone(value); if (cloned === undefined && value !== undefined) { delete target[key]; return; } target[key] = cloned; }',",
    "    'export class RlmStepRunner extends WorkerEntrypoint {',",
    "    '  async run() {',",
    "    '    const __globals = cloneValue(SNAPSHOT.globals ?? {});',",
    "    '    let __submitted;',",
    "    '    let __queryCallsUsed = SNAPSHOT.request.queryCallsUsed;',",
    "    '    const __logs = [];',",
    "    '    const __toolCalls = [];',",
    "    '    const inputs = SNAPSHOT.inlineInputs ?? {};',",
    "    '    const SUBMIT = async (value) => { __submitted = value; return value; };',",
    "    '    const print = (...args) => { __logs.push(args.map(__formatValue).join(\" \")); };',",
    "    '    const console = { log: (...args) => print(...args), warn: (...args) => print(...args), error: (...args) => print(...args) };',",
    "    '    const getInput = async (key) => key == null ? inputs : inputs[key];',",
    "    '    const getManifest = async () => SNAPSHOT.preparedContext?.manifest ?? null;',",
    "    '    const listResources = async () => SNAPSHOT.preparedContext?.resources ?? [];',",
    "    '    const __hostFetch = async (path, payload) => { const response = await fetch(`https://runtime.local${path}`, { method: \"POST\", headers: { \"content-type\": \"application/json\" }, body: JSON.stringify(payload) }); if (!response.ok) { throw new Error(await response.text()); } return response.json(); };',",
    "    '    const __readTextResource = async (path) => { const prepared = SNAPSHOT.preparedContext ?? {}; if (path === prepared.manifestPath) { const text = SNAPSHOT.textResources[path] ?? JSON.stringify(prepared.manifest ?? {}); return { path, storage: \"prepared\", text, totalChars: text.length, preview: text.slice(0, 240) }; } if (Object.prototype.hasOwnProperty.call(SNAPSHOT.textResources, path)) { const text = SNAPSHOT.textResources[path]; return { path, storage: \"prepared\", text, totalChars: text.length, preview: text.slice(0, 240) }; } const corpusMatch = pathMatchForCorpus(path); if (corpusMatch != null) { const response = await __hostFetch(\"/read-corpus-file\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId: corpusMatch.corpusId, path: corpusMatch.relativePath }); const text = response.content; return { path, storage: \"corpus\", text, totalChars: text.length, preview: text.slice(0, 240) }; } throw new Error(`Unknown prepared text path: ${path}`); };',",
    "    '    const __callTool = async (toolName, input, fn) => { const startedAt = nowIso(); try { const output = await fn(); __toolCalls.push({ toolName, input, output, source: \"rlm\", startedAt, endedAt: nowIso() }); return output; } catch (error) { const serialized = { message: error instanceof Error ? error.message : String(error) }; __toolCalls.push({ toolName, input, error: serialized, source: \"rlm\", startedAt, endedAt: nowIso() }); throw error; } };',",
    "    '    const query = async (prompt, options) => __callTool(\"rlm.query\", { prompt, options }, async () => { __queryCallsUsed += 1; if (__queryCallsUsed > SNAPSHOT.request.maxQueryCalls) throw new Error(`RLM query budget exceeded: ${__queryCallsUsed} > ${SNAPSHOT.request.maxQueryCalls}.`); const response = await __hostFetch(\"/query\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, prompt, options }); return response.text; });',",
    "    '    const llm_query = async (prompt, options) => query(prompt, options);',",
    "    '    const queryBatch = async (prompts, options) => __callTool(\"rlm.queryBatch\", { prompts, options }, async () => { __queryCallsUsed += prompts.length; if (__queryCallsUsed > SNAPSHOT.request.maxQueryCalls) throw new Error(`RLM query budget exceeded: ${__queryCallsUsed} > ${SNAPSHOT.request.maxQueryCalls}.`); const response = await __hostFetch(\"/query-batch\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, prompts, options }); return response.texts; });',",
    "    '    const llm_query_batched = async (prompts, options) => queryBatch(prompts, options);',",
    "    '    const getTextInfo = async (path) => __callTool(\"rlm.getTextInfo\", { path }, async () => { const resource = await __readTextResource(path); return { path: resource.path, storage: resource.storage, totalChars: resource.totalChars, preview: resource.preview }; });',",
    "    '    const readText = async (path, options = {}) => __callTool(\"rlm.readText\", { path, ...options }, async () => { const resource = await __readTextResource(path); return { path: resource.path, storage: resource.storage, ...readTextSlice(resource.text, options ?? {}, SNAPSHOT.request.maxOutputChars) }; });',",
    "    '    const searchText = async (path, queryText, options = {}) => __callTool(\"rlm.searchText\", { path, query: queryText, ...options }, async () => { const resource = await __readTextResource(path); return { storage: resource.storage, ...searchWithinText(resource.path, resource.text, queryText, options ?? {}) }; });',",
    "    '    const readMatchWindow = async (path, match, options = {}) => __callTool(\"rlm.readMatchWindow\", { path, match, ...options }, async () => { const resource = await __readTextResource(path); const beforeChars = Math.max(0, options.beforeChars ?? 80); const afterChars = Math.max(0, options.afterChars ?? 80); const startChar = Math.max(0, match.startChar - beforeChars); const defaultMaxChars = match.endChar - match.startChar + beforeChars + afterChars; return { path: resource.path, storage: resource.storage, ...readTextSlice(resource.text, { startChar, maxChars: options.maxChars ?? defaultMaxChars }, SNAPSHOT.request.maxOutputChars) }; });',",
    "    '    const listCorpusFiles = async (corpusId, prefix) => __callTool(\"rlm.listCorpusFiles\", prefix == null ? { corpusId } : { corpusId, prefix }, async () => { const response = await __hostFetch(\"/list-corpus-files\", prefix == null ? { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId } : { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, prefix }); return response.files; });',",
    "    '    const readCorpusFile = async (corpusId, path) => __callTool(\"rlm.readCorpusFile\", { corpusId, path }, async () => __hostFetch(\"/read-corpus-file\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, path }));',",
    "    '    const searchCorpus = async (corpusId, args = {}) => __callTool(\"rlm.searchCorpus\", { corpusId, ...(args ?? {}) }, async () => __hostFetch(\"/search-corpus\", { runId: SNAPSHOT.runId, moduleId: SNAPSHOT.moduleId, corpusId, ...(args ?? {}) }));',",
    "    trackedPrelude,",
    '    "    " + definitionPrelude,',
    "    inlineAliases,",
    "    toolAliases,",
    "    '    const tools = {',",
    "    toolObject.length > 0 ? `    ${toolObject}` : '',",
    "    '    };',",
    '    "    " + stepArgs.compiled.transformedCode,',
    "    trackedSync,",
    "    '    return { submitted: __submitted, queryCallsUsed: __queryCallsUsed, logs: __logs, stdout: __logs.length > 0 ? __logs.join(\"\\\\n\") : undefined, toolCalls: __toolCalls, globals: __globals };',",
    "    '  }',",
    "    '}',",
    "    cloneValue.toString(),",
    "].join('\\n');",
    "}",
    "",
    "export class RlmSessionFacet extends DurableObject {",
    "  constructor(ctx, env) {",
    "    super(ctx, env);",
    "    this.ctx = ctx;",
    "    this.env = env;",
    "    this.state = null;",
    "    this.ctx.blockConcurrencyWhile(async () => {",
    "      this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS session_state (state_key TEXT PRIMARY KEY, state_json TEXT NOT NULL, updated_at TEXT NOT NULL)`);",
    "      this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS session_step_journal (step_index INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL, result_json TEXT NOT NULL, created_at TEXT NOT NULL)`);",
    "    });",
    "  }",
    "",
    "  async __loadJson(key) {",
    "    const rows = this.ctx.storage.sql.exec('SELECT state_json FROM session_state WHERE state_key = ? LIMIT 1', key).toArray();",
    "    return rows[0] == null ? undefined : JSON.parse(rows[0].state_json);",
    "  }",
    "",
    "  async __saveJson(key, value) {",
    "    this.ctx.storage.sql.exec('INSERT OR REPLACE INTO session_state (state_key, state_json, updated_at) VALUES (?, ?, ?)', key, JSON.stringify(value), nowIso());",
    "  }",
    "",
    "  async __loadState() {",
    "    if (this.state != null) {",
    "      return this.state;",
    "    }",
    "    const state = (await this.__loadJson('session')) ?? null;",
    "    this.state = state;",
    "    return state;",
    "  }",
    "",
    "  async __saveState() {",
    "    if (this.state == null) {",
    "      return;",
    "    }",
    "    await this.__saveJson('session', this.state);",
    "  }",
    "",
    "  async init(args) {",
    "    this.state = {",
    "      runId: args.runId,",
    "      moduleId: args.moduleId,",
    "      preparedContext: args.preparedContext,",
    "      inlineInputs: args.inlineInputs,",
    "      textResources: args.textResources,",
    "      corpusIds: args.corpusIds,",
    "      tools: args.tools,",
    "      globals: {},",
    "      trackedNames: [],",
    "      definitionStatements: {},",
    "      coreCheckpoint: null,",
    "      lastUpdatedAt: nowIso(),",
    "    };",
    "    this.ctx.storage.sql.exec('DELETE FROM session_step_journal');",
    "    await this.__saveState();",
    "    return { ok: true };",
    "  }",
    "",
    "  async describe() {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    "      return { trackedNames: [] };",
    "    }",
    "    return { trackedNames: state.trackedNames ?? [] };",
    "  }",
    "",
    "  async exportState() {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    '      throw new Error("RLM facet session was not initialized.");',
    "    }",
    "    return cloneValue({",
    "      runId: state.runId,",
    "      moduleId: state.moduleId,",
    "      preparedContext: state.preparedContext,",
    "      inlineInputs: state.inlineInputs,",
    "      textResources: state.textResources ?? {},",
    "      globals: state.globals ?? {},",
    "      definitionStatements: state.definitionStatements ?? {},",
    "      tools: state.tools ?? [],",
    "    });",
    "  }",
    "",
    "  async applyStepResult(args) {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    '      throw new Error("RLM facet session was not initialized.");',
    "    }",
    "    const result = args.result ?? {};",
    "    state.globals = isRecord(result.globals) ? result.globals : {};",
    "    state.trackedNames = args.compiled.trackedNames ?? [];",
    "    const definitions = { ...(state.definitionStatements ?? {}) };",
    "    for (const name of args.compiled.declaredNames ?? []) {",
    "      if (Object.prototype.hasOwnProperty.call(state.globals, name)) {",
    "        delete definitions[name];",
    "      }",
    "    }",
    "    for (const entry of args.compiled.definitionStatements ?? []) {",
    "      definitions[entry.name] = entry.statement;",
    "    }",
    "    state.definitionStatements = definitions;",
    "    state.lastUpdatedAt = nowIso();",
    "    await this.__saveState();",
    "    this.ctx.storage.sql.exec('INSERT INTO session_step_journal (code, result_json, created_at) VALUES (?, ?, ?)', args.request.code, JSON.stringify({ logs: result.logs ?? [], submitted: result.submitted, error: result.error ?? null, toolCalls: result.toolCalls ?? [], queryCallsUsed: result.queryCallsUsed ?? args.request.queryCallsUsed }), nowIso());",
    "    return { ok: true };",
    "  }",
    "",
    "  async checkpoint(checkpoint) {",
    "    const state = await this.__loadState();",
    "    if (state == null) {",
    "      return;",
    "    }",
    "    state.coreCheckpoint = checkpoint;",
    "    state.lastUpdatedAt = nowIso();",
    "    await this.__saveState();",
    "  }",
    "",
    "  async resume() {",
    "    const state = await this.__loadState();",
    "    return state?.coreCheckpoint ?? null;",
    "  }",
    "",
    "  async close() {",
    "    return { ok: true };",
    "  }",
    "}",
  ].join("\n");
}
