import {
  IconAlertInfoFill18,
  IconApartmentBuildingFill18,
  IconArrowDownFill18,
  IconArrowLeftFill18,
  IconArrowRightFill18,
  IconArrowUpFill18,
  IconBookOpenFill18,
  IconCameraFill18,
  IconCaretDownFill18,
  IconCaretLeftFill18,
  IconCaretRightFill18,
  IconCaretUpFill18,
  IconCheckFill18,
  IconChevronExpandYFill18,
  IconCircleCheck3Fill18,
  IconCircleDotsFill18,
  IconCircleDottedFill18,
  IconCirclePauseFill18,
  IconCirclePlayFill18,
  IconCircleQuestionFill18,
  IconCircleStopFill18,
  IconCircleXmarkFill18,
  IconClipboardFill18,
  IconClockPlusFill18,
  IconCodeActionFill18,
  IconCodeBranchFill18,
  IconCodeCommitFill18,
  IconCopyIdFill18,
  IconDownloadFill18,
  IconDotsFill18,
  IconDiscountTagFill18,
  IconEditCircleFill18,
  IconEditSquareFill18,
  IconEngineFill18,
  IconExternalLinkFill18,
  IconEyeFill18,
  IconEyeSlashFill18,
  IconFileFill18,
  IconFilesFill18,
  IconFolderFill18,
  IconFolderOpenFill18,
  IconFilterFill18,
  IconFilterOffFill18,
  IconGear3Fill18,
  IconGlobeFill18,
  IconImageSparkleFill18,
  IconKey2Fill18,
  IconLinkFill18,
  IconLoader2Fill18,
  IconLoaderFill18,
  IconMagicWandFill18,
  IconMenuFill18,
  IconMinusFill18,
  IconMobile2Fill18,
  IconMoonFill18,
  IconMsgFill18,
  IconMsgsFill18,
  IconPlusFill18,
  IconMagnifierFill18,
  IconRefreshFill18,
  IconRectLayoutGridFill18,
  IconShareRightFill18,
  IconSidebarLeftFill18,
  IconSparkleFill18,
  IconSunFill18,
  IconTerminalFill18,
  IconTrash2Fill18,
  IconTriangleWarningFill18,
  IconUpload4Fill18,
  IconUserFill18,
  IconUserSparkleFill18,
  IconUsers2Fill18,
  IconUsersSeparationFill18,
  IconWrenchFill18,
  IconXmarkFill18,
  IconMediaPlayFill18,
  IconCalculatorFill18,
  IconCalculator2Fill18,
  IconSuitcase5Fill18,
  IconSteeringWheelFill18,
  IconHouse4Fill18,
} from "nucleo-ui-fill-18";
import {
  IconAlertInfoFillDuo18,
  IconApartmentBuildingFillDuo18,
  IconArrowDownFillDuo18,
  IconArrowLeftFillDuo18,
  IconArrowRightFillDuo18,
  IconArrowUpFillDuo18,
  IconBookOpenFillDuo18,
  IconCameraFillDuo18,
  IconCaretDownFillDuo18,
  IconCaretLeftFillDuo18,
  IconCaretRightFillDuo18,
  IconCaretUpFillDuo18,
  IconCheckFillDuo18,
  IconChevronExpandYFillDuo18,
  IconCircleCheck3FillDuo18,
  IconCircleDotsFillDuo18,
  IconCircleDottedFillDuo18,
  IconCirclePauseFillDuo18,
  IconCirclePlayFillDuo18,
  IconCircleQuestionFillDuo18,
  IconCircleStopFillDuo18,
  IconCircleXmarkFillDuo18,
  IconClipboardFillDuo18,
  IconClockPlusFillDuo18,
  IconCodeActionFillDuo18,
  IconCodeBranchFillDuo18,
  IconCodeCommitFillDuo18,
  IconCopyIdFillDuo18,
  IconDownloadFillDuo18,
  IconDotsFillDuo18,
  IconDiscountTagFillDuo18,
  IconEditCircleFillDuo18,
  IconEditSquareFillDuo18,
  IconEngineFillDuo18,
  IconExternalLinkFillDuo18,
  IconEyeFillDuo18,
  IconEyeSlashFillDuo18,
  IconFileFillDuo18,
  IconFilesFillDuo18,
  IconFolderFillDuo18,
  IconFolderOpenFillDuo18,
  IconFilterFillDuo18,
  IconFilterOffFillDuo18,
  IconGear3FillDuo18,
  IconGlobeFillDuo18,
  IconImageSparkleFillDuo18,
  IconKey2FillDuo18,
  IconLinkFillDuo18,
  IconLoader2FillDuo18,
  IconLoaderFillDuo18,
  IconMagicWandFillDuo18,
  IconMenuFillDuo18,
  IconMinusFillDuo18,
  IconMobile2FillDuo18,
  IconMoonFillDuo18,
  IconMsgFillDuo18,
  IconMsgsFillDuo18,
  IconPlusFillDuo18,
  IconQuickSearchFillDuo18,
  IconMagnifier2FillDuo18,
  IconRefreshFillDuo18,
  IconRectLayoutGridFillDuo18,
  IconShareRightFillDuo18,
  IconSidebarLeftFillDuo18,
  IconSparkleFillDuo18,
  IconSunFillDuo18,
  IconTerminalFillDuo18,
  IconTrash2FillDuo18,
  IconTriangleWarningFillDuo18,
  IconUpload4FillDuo18,
  IconUserFillDuo18,
  IconUserSparkleFillDuo18,
  IconUsers2FillDuo18,
  IconUsersSeparationFillDuo18,
  IconWrenchFillDuo18,
  IconXmarkFillDuo18,
  IconMagnifierFillDuo18,
  IconMediaPlayFillDuo18,
  IconCalculatorFillDuo18,
  IconCalculator2FillDuo18,
  IconSuitcase5FillDuo18,
  IconSteeringWheelFillDuo18,
  IconHouse4FillDuo18,
} from "nucleo-ui-fill-duo-18";
import {
  IconAlertInfoOutline18,
  IconApartmentBuildingOutline18,
  IconArrowDownOutline18,
  IconArrowLeftOutline18,
  IconArrowRightOutline18,
  IconArrowUpOutline18,
  IconBookOpenOutline18,
  IconCameraOutline18,
  IconCaretDownOutline18,
  IconCaretLeftOutline18,
  IconCaretRightOutline18,
  IconCaretUpOutline18,
  IconCheckOutline18,
  IconChevronExpandYOutline18,
  IconCircleCheck3Outline18,
  IconCircleDotsOutline18,
  IconCircleDottedOutline18,
  IconCirclePauseOutline18,
  IconCirclePlayOutline18,
  IconCircleQuestionOutline18,
  IconCircleStopOutline18,
  IconCircleXmarkOutline18,
  IconClipboardOutline18,
  IconClockPlusOutline18,
  IconCodeActionOutline18,
  IconCodeBranchOutline18,
  IconCodeCommitOutline18,
  IconCopyIdOutline18,
  IconDownloadOutline18,
  IconDotsOutline18,
  IconDiscountTagOutline18,
  IconEditCircleOutline18,
  IconEditSquareOutline18,
  IconEngineOutline18,
  IconExternalLinkOutline18,
  IconEyeOutline18,
  IconEyeSlashOutline18,
  IconFileOutline18,
  IconFilesOutline18,
  IconFolderOutline18,
  IconFolderOpenOutline18,
  IconFilterOffOutline18,
  IconFilterOutline18,
  IconGear3Outline18,
  IconGlobeOutline18,
  IconImageSparkleOutline18,
  IconKey2Outline18,
  IconLinkOutline18,
  IconLoader2Outline18,
  IconLoaderOutline18,
  IconMagicWandOutline18,
  IconMenuOutline18,
  IconMinusOutline18,
  IconMobile2Outline18,
  IconMoonOutline18,
  IconMsgOutline18,
  IconMsgsOutline18,
  IconPlusOutline18,
  IconQuickSearchOutline18,
  IconMagnifier2Outline18,
  IconRefreshOutline18,
  IconRectLayoutGridOutline18,
  IconShareRightOutline18,
  IconSidebarLeftOutline18,
  IconSparkleOutline18,
  IconSunOutline18,
  IconTerminalOutline18,
  IconTrash2Outline18,
  IconTriangleWarningOutline18,
  IconUpload4Outline18,
  IconUserOutline18,
  IconUserSparkleOutline18,
  IconUsers2Outline18,
  IconUsersSeparationOutline18,
  IconWrenchOutline18,
  IconXmarkOutline18,
  IconMagnifierOutline18,
  IconMediaPlayOutline18,
  IconCalculatorOutline18,
  IconCalculator2Outline18,
  IconSuitcase5Outline18,
  IconSteeringWheelOutline18,
  IconHouse4Outline18,
} from "nucleo-ui-outline-18";
import {
  IconAlertInfoOutlineDuo18,
  IconApartmentBuildingOutlineDuo18,
  IconArrowDownOutlineDuo18,
  IconArrowLeftOutlineDuo18,
  IconArrowRightOutlineDuo18,
  IconArrowUpOutlineDuo18,
  IconBookOpenOutlineDuo18,
  IconCameraOutlineDuo18,
  IconCaretDownOutlineDuo18,
  IconCaretLeftOutlineDuo18,
  IconCaretRightOutlineDuo18,
  IconCaretUpOutlineDuo18,
  IconCheckOutlineDuo18,
  IconChevronExpandYOutlineDuo18,
  IconCircleCheck3OutlineDuo18,
  IconCircleDotsOutlineDuo18,
  IconCircleDottedOutlineDuo18,
  IconCirclePauseOutlineDuo18,
  IconCirclePlayOutlineDuo18,
  IconCircleQuestionOutlineDuo18,
  IconCircleStopOutlineDuo18,
  IconCircleXmarkOutlineDuo18,
  IconClipboardOutlineDuo18,
  IconClockPlusOutlineDuo18,
  IconCodeActionOutlineDuo18,
  IconCodeBranchOutlineDuo18,
  IconCodeCommitOutlineDuo18,
  IconCopyIdOutlineDuo18,
  IconDownloadOutlineDuo18,
  IconDotsOutlineDuo18,
  IconDiscountTagOutlineDuo18,
  IconEditCircleOutlineDuo18,
  IconEditSquareOutlineDuo18,
  IconEngineOutlineDuo18,
  IconExternalLinkOutlineDuo18,
  IconEyeOutlineDuo18,
  IconEyeSlashOutlineDuo18,
  IconFileOutlineDuo18,
  IconFilesOutlineDuo18,
  IconFolderOutlineDuo18,
  IconFolderOpenOutlineDuo18,
  IconFilterOffOutlineDuo18,
  IconFilterOutlineDuo18,
  IconGear3OutlineDuo18,
  IconGlobeOutlineDuo18,
  IconImageSparkleOutlineDuo18,
  IconKey2OutlineDuo18,
  IconLinkOutlineDuo18,
  IconLoader2OutlineDuo18,
  IconLoaderOutlineDuo18,
  IconMagicWandOutlineDuo18,
  IconMenuOutlineDuo18,
  IconMinusOutlineDuo18,
  IconMobile2OutlineDuo18,
  IconMoonOutlineDuo18,
  IconMsgOutlineDuo18,
  IconMsgsOutlineDuo18,
  IconPlusOutlineDuo18,
  IconQuickSearchOutlineDuo18,
  IconMagnifier2OutlineDuo18,
  IconRefreshOutlineDuo18,
  IconRectLayoutGridOutlineDuo18,
  IconShareRightOutlineDuo18,
  IconSidebarLeftOutlineDuo18,
  IconSparkleOutlineDuo18,
  IconSunOutlineDuo18,
  IconTerminalOutlineDuo18,
  IconTrash2OutlineDuo18,
  IconTriangleWarningOutlineDuo18,
  IconUpload4OutlineDuo18,
  IconUserOutlineDuo18,
  IconUserSparkleOutlineDuo18,
  IconUsers2OutlineDuo18,
  IconUsersSeparationOutlineDuo18,
  IconWrenchOutlineDuo18,
  IconXmarkOutlineDuo18,
  IconMagnifierOutlineDuo18,
  IconMediaPlayOutlineDuo18,
  IconCalculatorOutlineDuo18,
  IconCalculator2OutlineDuo18,
  IconSuitcase5OutlineDuo18,
  IconSteeringWheelOutlineDuo18,
  IconHouse4OutlineDuo18,
} from "nucleo-ui-outline-duo-18";
import type { ComponentType, CSSProperties, SVGProps } from "react";

export type IconVariant = "fill" | "fillduo" | "outline" | "outlineduo";

const DEFAULT_ICON_VARIANT: IconVariant = "outlineduo";

export type IconProps = SVGProps<SVGSVGElement> & {
  absoluteStrokeWidth?: boolean;
  size?: number | string;
  strokeWidth?: number;
  variant?: IconVariant;
};

type NucleoIconComponent = ComponentType<SVGProps<SVGSVGElement>>;
export type IconComponent = ComponentType<IconProps>;
type IconSet = Record<IconVariant, NucleoIconComponent>;

const toCssSize = (size: number | string | undefined) =>
  typeof size === "number" ? `${size}px` : size;

const createIcon = (name: string, iconSet: IconSet): IconComponent => {
  const WrappedIcon = ({
    absoluteStrokeWidth,
    color,
    size,
    style,
    strokeWidth = 1.2,
    variant,
    ...rest
  }: IconProps) => {
    void absoluteStrokeWidth;
    const BaseIcon = iconSet[variant ?? DEFAULT_ICON_VARIANT];
    const cssSize = toCssSize(size);
    const mergedStyle: CSSProperties = {
      ...style,
      ...(cssSize ? { height: cssSize, width: cssSize } : {}),
      ...(color ? { color } : {}),
    };

    return <BaseIcon {...rest} strokeWidth={strokeWidth} style={mergedStyle} />;
  };

  WrappedIcon.displayName = `Icon.${name}`;
  return WrappedIcon;
};

const iconDefinitions = {
  Add: {
    fill: IconPlusFill18,
    fillduo: IconPlusFillDuo18,
    outline: IconPlusOutline18,
    outlineduo: IconPlusOutlineDuo18,
  },
  ArrowDown: {
    fill: IconArrowDownFill18,
    fillduo: IconArrowDownFillDuo18,
    outline: IconArrowDownOutline18,
    outlineduo: IconArrowDownOutlineDuo18,
  },
  ArrowLeft: {
    fill: IconArrowLeftFill18,
    fillduo: IconArrowLeftFillDuo18,
    outline: IconArrowLeftOutline18,
    outlineduo: IconArrowLeftOutlineDuo18,
  },
  ArrowRight: {
    fill: IconArrowRightFill18,
    fillduo: IconArrowRightFillDuo18,
    outline: IconArrowRightOutline18,
    outlineduo: IconArrowRightOutlineDuo18,
  },
  ArrowUp: {
    fill: IconArrowUpFill18,
    fillduo: IconArrowUpFillDuo18,
    outline: IconArrowUpOutline18,
    outlineduo: IconArrowUpOutlineDuo18,
  },
  Building: {
    fill: IconApartmentBuildingFill18,
    fillduo: IconApartmentBuildingFillDuo18,
    outline: IconApartmentBuildingOutline18,
    outlineduo: IconApartmentBuildingOutlineDuo18,
  },
  Book: {
    fill: IconBookOpenFill18,
    fillduo: IconBookOpenFillDuo18,
    outline: IconBookOpenOutline18,
    outlineduo: IconBookOpenOutlineDuo18,
  },
  BookOpen: {
    fill: IconBookOpenFill18,
    fillduo: IconBookOpenFillDuo18,
    outline: IconBookOpenOutline18,
    outlineduo: IconBookOpenOutlineDuo18,
  },
  Branch: {
    fill: IconCodeBranchFill18,
    fillduo: IconCodeBranchFillDuo18,
    outline: IconCodeBranchOutline18,
    outlineduo: IconCodeBranchOutlineDuo18,
  },
  Camera: {
    fill: IconCameraFill18,
    fillduo: IconCameraFillDuo18,
    outline: IconCameraOutline18,
    outlineduo: IconCameraOutlineDuo18,
  },
  Chat: {
    fill: IconMsgsFill18,
    fillduo: IconMsgsFillDuo18,
    outline: IconMsgsOutline18,
    outlineduo: IconMsgsOutlineDuo18,
  },
  Check: {
    fill: IconCheckFill18,
    fillduo: IconCheckFillDuo18,
    outline: IconCheckOutline18,
    outlineduo: IconCheckOutlineDuo18,
  },
  ChevronDown: {
    fill: IconCaretDownFill18,
    fillduo: IconCaretDownFillDuo18,
    outline: IconCaretDownOutline18,
    outlineduo: IconCaretDownOutlineDuo18,
  },
  ChevronExpandY: {
    fill: IconChevronExpandYFill18,
    fillduo: IconChevronExpandYFillDuo18,
    outline: IconChevronExpandYOutline18,
    outlineduo: IconChevronExpandYOutlineDuo18,
  },
  ChevronLeft: {
    fill: IconCaretLeftFill18,
    fillduo: IconCaretLeftFillDuo18,
    outline: IconCaretLeftOutline18,
    outlineduo: IconCaretLeftOutlineDuo18,
  },
  ChevronRight: {
    fill: IconCaretRightFill18,
    fillduo: IconCaretRightFillDuo18,
    outline: IconCaretRightOutline18,
    outlineduo: IconCaretRightOutlineDuo18,
  },
  ChevronUp: {
    fill: IconCaretUpFill18,
    fillduo: IconCaretUpFillDuo18,
    outline: IconCaretUpOutline18,
    outlineduo: IconCaretUpOutlineDuo18,
  },
  Circle: {
    fill: IconCircleDottedFill18,
    fillduo: IconCircleDottedFillDuo18,
    outline: IconCircleDottedOutline18,
    outlineduo: IconCircleDottedOutlineDuo18,
  },
  CircleX: {
    fill: IconCircleXmarkFill18,
    fillduo: IconCircleXmarkFillDuo18,
    outline: IconCircleXmarkOutline18,
    outlineduo: IconCircleXmarkOutlineDuo18,
  },
  Clipboard: {
    fill: IconClipboardFill18,
    fillduo: IconClipboardFillDuo18,
    outline: IconClipboardOutline18,
    outlineduo: IconClipboardOutlineDuo18,
  },
  Clock: {
    fill: IconClockPlusFill18,
    fillduo: IconClockPlusFillDuo18,
    outline: IconClockPlusOutline18,
    outlineduo: IconClockPlusOutlineDuo18,
  },
  Close: {
    fill: IconXmarkFill18,
    fillduo: IconXmarkFillDuo18,
    outline: IconXmarkOutline18,
    outlineduo: IconXmarkOutlineDuo18,
  },
  Code: {
    fill: IconCodeActionFill18,
    fillduo: IconCodeActionFillDuo18,
    outline: IconCodeActionOutline18,
    outlineduo: IconCodeActionOutlineDuo18,
  },
  Commit: {
    fill: IconCodeCommitFill18,
    fillduo: IconCodeCommitFillDuo18,
    outline: IconCodeCommitOutline18,
    outlineduo: IconCodeCommitOutlineDuo18,
  },
  Copy: {
    fill: IconCopyIdFill18,
    fillduo: IconCopyIdFillDuo18,
    outline: IconCopyIdOutline18,
    outlineduo: IconCopyIdOutlineDuo18,
  },
  Danger: {
    fill: IconXmarkFill18,
    fillduo: IconXmarkFillDuo18,
    outline: IconXmarkOutline18,
    outlineduo: IconXmarkOutlineDuo18,
  },
  Dot: {
    fill: IconCircleDotsFill18,
    fillduo: IconCircleDotsFillDuo18,
    outline: IconCircleDotsOutline18,
    outlineduo: IconCircleDotsOutlineDuo18,
  },
  Download: {
    fill: IconDownloadFill18,
    fillduo: IconDownloadFillDuo18,
    outline: IconDownloadOutline18,
    outlineduo: IconDownloadOutlineDuo18,
  },
  Dots: {
    fill: IconDotsFill18,
    fillduo: IconDotsFillDuo18,
    outline: IconDotsOutline18,
    outlineduo: IconDotsOutlineDuo18,
  },
  Edit: {
    fill: IconEditSquareFill18,
    fillduo: IconEditSquareFillDuo18,
    outline: IconEditSquareOutline18,
    outlineduo: IconEditSquareOutlineDuo18,
  },
  Engine: {
    fill: IconEngineFill18,
    fillduo: IconEngineFillDuo18,
    outline: IconEngineOutline18,
    outlineduo: IconEngineOutlineDuo18,
  },
  ExternalLink: {
    fill: IconExternalLinkFill18,
    fillduo: IconExternalLinkFillDuo18,
    outline: IconExternalLinkOutline18,
    outlineduo: IconExternalLinkOutlineDuo18,
  },
  Eye: {
    fill: IconEyeFill18,
    fillduo: IconEyeFillDuo18,
    outline: IconEyeOutline18,
    outlineduo: IconEyeOutlineDuo18,
  },
  EyeOff: {
    fill: IconEyeSlashFill18,
    fillduo: IconEyeSlashFillDuo18,
    outline: IconEyeSlashOutline18,
    outlineduo: IconEyeSlashOutlineDuo18,
  },
  File: {
    fill: IconFileFill18,
    fillduo: IconFileFillDuo18,
    outline: IconFileOutline18,
    outlineduo: IconFileOutlineDuo18,
  },
  Files: {
    fill: IconFilesFill18,
    fillduo: IconFilesFillDuo18,
    outline: IconFilesOutline18,
    outlineduo: IconFilesOutlineDuo18,
  },
  Folder: {
    fill: IconFolderFill18,
    fillduo: IconFolderFillDuo18,
    outline: IconFolderOutline18,
    outlineduo: IconFolderOutlineDuo18,
  },
  FolderOpen: {
    fill: IconFolderOpenFill18,
    fillduo: IconFolderOpenFillDuo18,
    outline: IconFolderOpenOutline18,
    outlineduo: IconFolderOpenOutlineDuo18,
  },
  Grid: {
    fill: IconRectLayoutGridFill18,
    fillduo: IconRectLayoutGridFillDuo18,
    outline: IconRectLayoutGridOutline18,
    outlineduo: IconRectLayoutGridOutlineDuo18,
  },
  Filter: {
    fill: IconFilterFill18,
    fillduo: IconFilterFillDuo18,
    outline: IconFilterOutline18,
    outlineduo: IconFilterOutlineDuo18,
  },
  FilterOff: {
    fill: IconFilterOffFill18,
    fillduo: IconFilterOffFillDuo18,
    outline: IconFilterOffOutline18,
    outlineduo: IconFilterOffOutlineDuo18,
  },
  Globe: {
    fill: IconGlobeFill18,
    fillduo: IconGlobeFillDuo18,
    outline: IconGlobeOutline18,
    outlineduo: IconGlobeOutlineDuo18,
  },
  Image: {
    fill: IconImageSparkleFill18,
    fillduo: IconImageSparkleFillDuo18,
    outline: IconImageSparkleOutline18,
    outlineduo: IconImageSparkleOutlineDuo18,
  },
  Info: {
    fill: IconAlertInfoFill18,
    fillduo: IconAlertInfoFillDuo18,
    outline: IconAlertInfoOutline18,
    outlineduo: IconAlertInfoOutlineDuo18,
  },
  Key: {
    fill: IconKey2Fill18,
    fillduo: IconKey2FillDuo18,
    outline: IconKey2Outline18,
    outlineduo: IconKey2OutlineDuo18,
  },
  Link: {
    fill: IconLinkFill18,
    fillduo: IconLinkFillDuo18,
    outline: IconLinkOutline18,
    outlineduo: IconLinkOutlineDuo18,
  },
  Loader2: {
    fill: IconLoader2Fill18,
    fillduo: IconLoader2FillDuo18,
    outline: IconLoader2Outline18,
    outlineduo: IconLoader2OutlineDuo18,
  },
  Loader: {
    fill: IconLoaderFill18,
    fillduo: IconLoaderFillDuo18,
    outline: IconLoaderOutline18,
    outlineduo: IconLoaderOutlineDuo18,
  },
  Magic: {
    fill: IconMagicWandFill18,
    fillduo: IconMagicWandFillDuo18,
    outline: IconMagicWandOutline18,
    outlineduo: IconMagicWandOutlineDuo18,
  },
  Menu: {
    fill: IconMenuFill18,
    fillduo: IconMenuFillDuo18,
    outline: IconMenuOutline18,
    outlineduo: IconMenuOutlineDuo18,
  },
  Message: {
    fill: IconMsgFill18,
    fillduo: IconMsgFillDuo18,
    outline: IconMsgOutline18,
    outlineduo: IconMsgOutlineDuo18,
  },
  Mobile: {
    fill: IconMobile2Fill18,
    fillduo: IconMobile2FillDuo18,
    outline: IconMobile2Outline18,
    outlineduo: IconMobile2OutlineDuo18,
  },
  Moon: {
    fill: IconMoonFill18,
    fillduo: IconMoonFillDuo18,
    outline: IconMoonOutline18,
    outlineduo: IconMoonOutlineDuo18,
  },
  Pause: {
    fill: IconCirclePauseFill18,
    fillduo: IconCirclePauseFillDuo18,
    outline: IconCirclePauseOutline18,
    outlineduo: IconCirclePauseOutlineDuo18,
  },
  Play: {
    fill: IconMediaPlayFill18,
    fillduo: IconMediaPlayFillDuo18,
    outline: IconMediaPlayOutline18,
    outlineduo: IconMediaPlayOutlineDuo18,
  },
  Question: {
    fill: IconCircleQuestionFill18,
    fillduo: IconCircleQuestionFillDuo18,
    outline: IconCircleQuestionOutline18,
    outlineduo: IconCircleQuestionOutlineDuo18,
  },
  Refresh: {
    fill: IconRefreshFill18,
    fillduo: IconRefreshFillDuo18,
    outline: IconRefreshOutline18,
    outlineduo: IconRefreshOutlineDuo18,
  },
  Remove: {
    fill: IconMinusFill18,
    fillduo: IconMinusFillDuo18,
    outline: IconMinusOutline18,
    outlineduo: IconMinusOutlineDuo18,
  },
  Rename: {
    fill: IconEditCircleFill18,
    fillduo: IconEditCircleFillDuo18,
    outline: IconEditCircleOutline18,
    outlineduo: IconEditCircleOutlineDuo18,
  },
  Search: {
    fill: IconMagnifierFill18,
    fillduo: IconMagnifierFillDuo18,
    outline: IconMagnifierOutline18,
    outlineduo: IconMagnifierOutlineDuo18,
  },
  Gear3: {
    fill: IconGear3Fill18,
    fillduo: IconGear3FillDuo18,
    outline: IconGear3Outline18,
    outlineduo: IconGear3OutlineDuo18,
  },
  Share: {
    fill: IconShareRightFill18,
    fillduo: IconShareRightFillDuo18,
    outline: IconShareRightOutline18,
    outlineduo: IconShareRightOutlineDuo18,
  },
  Sidebar: {
    fill: IconSidebarLeftFill18,
    fillduo: IconSidebarLeftFillDuo18,
    outline: IconSidebarLeftOutline18,
    outlineduo: IconSidebarLeftOutlineDuo18,
  },
  Sparkle: {
    fill: IconSparkleFill18,
    fillduo: IconSparkleFillDuo18,
    outline: IconSparkleOutline18,
    outlineduo: IconSparkleOutlineDuo18,
  },
  Stop: {
    fill: IconCircleStopFill18,
    fillduo: IconCircleStopFillDuo18,
    outline: IconCircleStopOutline18,
    outlineduo: IconCircleStopOutlineDuo18,
  },
  Success: {
    fill: IconCircleCheck3Fill18,
    fillduo: IconCircleCheck3FillDuo18,
    outline: IconCircleCheck3Outline18,
    outlineduo: IconCircleCheck3OutlineDuo18,
  },
  Sun: {
    fill: IconSunFill18,
    fillduo: IconSunFillDuo18,
    outline: IconSunOutline18,
    outlineduo: IconSunOutlineDuo18,
  },
  Tag: {
    fill: IconDiscountTagFill18,
    fillduo: IconDiscountTagFillDuo18,
    outline: IconDiscountTagOutline18,
    outlineduo: IconDiscountTagOutlineDuo18,
  },
  Terminal: {
    fill: IconTerminalFill18,
    fillduo: IconTerminalFillDuo18,
    outline: IconTerminalOutline18,
    outlineduo: IconTerminalOutlineDuo18,
  },
  Trash: {
    fill: IconTrash2Fill18,
    fillduo: IconTrash2FillDuo18,
    outline: IconTrash2Outline18,
    outlineduo: IconTrash2OutlineDuo18,
  },
  Upload: {
    fill: IconUpload4Fill18,
    fillduo: IconUpload4FillDuo18,
    outline: IconUpload4Outline18,
    outlineduo: IconUpload4OutlineDuo18,
  },
  Agent: {
    fill: IconUserSparkleFill18,
    fillduo: IconUserSparkleFillDuo18,
    outline: IconUserSparkleOutline18,
    outlineduo: IconUserSparkleOutlineDuo18,
  },
  User: {
    fill: IconUserFill18,
    fillduo: IconUserFillDuo18,
    outline: IconUserOutline18,
    outlineduo: IconUserOutlineDuo18,
  },
  Users: {
    fill: IconUsers2Fill18,
    fillduo: IconUsers2FillDuo18,
    outline: IconUsers2Outline18,
    outlineduo: IconUsers2OutlineDuo18,
  },
  UsersSeparation: {
    fill: IconUsersSeparationFill18,
    fillduo: IconUsersSeparationFillDuo18,
    outline: IconUsersSeparationOutline18,
    outlineduo: IconUsersSeparationOutlineDuo18,
  },
  Warning: {
    fill: IconTriangleWarningFill18,
    fillduo: IconTriangleWarningFillDuo18,
    outline: IconTriangleWarningOutline18,
    outlineduo: IconTriangleWarningOutlineDuo18,
  },
  Wrench: {
    fill: IconWrenchFill18,
    fillduo: IconWrenchFillDuo18,
    outline: IconWrenchOutline18,
    outlineduo: IconWrenchOutlineDuo18,
  },
  Calculator: {
    fill: IconCalculator2Fill18,
    fillduo: IconCalculator2FillDuo18,
    outline: IconCalculator2Outline18,
    outlineduo: IconCalculator2OutlineDuo18,
  },
  Suitcase: {
    fill: IconSuitcase5Fill18,
    fillduo: IconSuitcase5FillDuo18,
    outline: IconSuitcase5Outline18,
    outlineduo: IconSuitcase5OutlineDuo18,
  },
  SteeringWheel: {
    fill: IconSteeringWheelFill18,
    fillduo: IconSteeringWheelFillDuo18,
    outline: IconSteeringWheelOutline18,
    outlineduo: IconSteeringWheelOutlineDuo18,
  },
  House: {
    fill: IconHouse4Fill18,
    fillduo: IconHouse4FillDuo18,
    outline: IconHouse4Outline18,
    outlineduo: IconHouse4OutlineDuo18,
  },
} as const satisfies Record<string, IconSet>;

const createIcons = <TIconDefinitions extends Record<string, IconSet>>(
  definitions: TIconDefinitions,
) =>
  Object.fromEntries(
    Object.entries(definitions).map(([name, iconSet]) => [name, createIcon(name, iconSet)]),
  ) as {
    [TKey in keyof TIconDefinitions]: IconComponent;
  };

export const Icon = {
  ...createIcons(iconDefinitions),
};
