/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardPlaygroundRouteImport } from './routes/_dashboard/playground'
import { Route as DashboardOptimizationRouteImport } from './routes/_dashboard/optimization'
import { Route as DashboardTracesRouteRouteImport } from './routes/_dashboard/traces/route'
import { Route as DashboardAgentsRouteRouteImport } from './routes/_dashboard/agents/route'
import { Route as DashboardTracesIndexRouteImport } from './routes/_dashboard/traces/index'
import { Route as DashboardTracesTraceIdRouteImport } from './routes/_dashboard/traces/$traceId'
import { Route as DashboardAgentsAgentNameRouteImport } from './routes/_dashboard/agents/$agentName'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOptimizationRoute = DashboardOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTracesRouteRoute = DashboardTracesRouteRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsRouteRoute = DashboardAgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTracesIndexRoute = DashboardTracesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTracesRouteRoute,
} as any)
const DashboardTracesTraceIdRoute = DashboardTracesTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => DashboardTracesRouteRoute,
} as any)
const DashboardAgentsAgentNameRoute =
  DashboardAgentsAgentNameRouteImport.update({
    id: '/$agentName',
    path: '/$agentName',
    getParentRoute: () => DashboardAgentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/agents': typeof DashboardAgentsRouteRouteWithChildren
  '/traces': typeof DashboardTracesRouteRouteWithChildren
  '/optimization': typeof DashboardOptimizationRoute
  '/playground': typeof DashboardPlaygroundRoute
  '/agents/$agentName': typeof DashboardAgentsAgentNameRoute
  '/traces/$traceId': typeof DashboardTracesTraceIdRoute
  '/traces/': typeof DashboardTracesIndexRoute
}
export interface FileRoutesByTo {
  '/agents': typeof DashboardAgentsRouteRouteWithChildren
  '/optimization': typeof DashboardOptimizationRoute
  '/playground': typeof DashboardPlaygroundRoute
  '/': typeof DashboardIndexRoute
  '/agents/$agentName': typeof DashboardAgentsAgentNameRoute
  '/traces/$traceId': typeof DashboardTracesTraceIdRoute
  '/traces': typeof DashboardTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/agents': typeof DashboardAgentsRouteRouteWithChildren
  '/_dashboard/traces': typeof DashboardTracesRouteRouteWithChildren
  '/_dashboard/optimization': typeof DashboardOptimizationRoute
  '/_dashboard/playground': typeof DashboardPlaygroundRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/agents/$agentName': typeof DashboardAgentsAgentNameRoute
  '/_dashboard/traces/$traceId': typeof DashboardTracesTraceIdRoute
  '/_dashboard/traces/': typeof DashboardTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/traces'
    | '/optimization'
    | '/playground'
    | '/agents/$agentName'
    | '/traces/$traceId'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/optimization'
    | '/playground'
    | '/'
    | '/agents/$agentName'
    | '/traces/$traceId'
    | '/traces'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/agents'
    | '/_dashboard/traces'
    | '/_dashboard/optimization'
    | '/_dashboard/playground'
    | '/_dashboard/'
    | '/_dashboard/agents/$agentName'
    | '/_dashboard/traces/$traceId'
    | '/_dashboard/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/playground': {
      id: '/_dashboard/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/optimization': {
      id: '/_dashboard/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof DashboardOptimizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/traces': {
      id: '/_dashboard/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof DashboardTracesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/traces/': {
      id: '/_dashboard/traces/'
      path: '/'
      fullPath: '/traces/'
      preLoaderRoute: typeof DashboardTracesIndexRouteImport
      parentRoute: typeof DashboardTracesRouteRoute
    }
    '/_dashboard/traces/$traceId': {
      id: '/_dashboard/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof DashboardTracesTraceIdRouteImport
      parentRoute: typeof DashboardTracesRouteRoute
    }
    '/_dashboard/agents/$agentName': {
      id: '/_dashboard/agents/$agentName'
      path: '/$agentName'
      fullPath: '/agents/$agentName'
      preLoaderRoute: typeof DashboardAgentsAgentNameRouteImport
      parentRoute: typeof DashboardAgentsRouteRoute
    }
  }
}

interface DashboardAgentsRouteRouteChildren {
  DashboardAgentsAgentNameRoute: typeof DashboardAgentsAgentNameRoute
}

const DashboardAgentsRouteRouteChildren: DashboardAgentsRouteRouteChildren = {
  DashboardAgentsAgentNameRoute: DashboardAgentsAgentNameRoute,
}

const DashboardAgentsRouteRouteWithChildren =
  DashboardAgentsRouteRoute._addFileChildren(DashboardAgentsRouteRouteChildren)

interface DashboardTracesRouteRouteChildren {
  DashboardTracesTraceIdRoute: typeof DashboardTracesTraceIdRoute
  DashboardTracesIndexRoute: typeof DashboardTracesIndexRoute
}

const DashboardTracesRouteRouteChildren: DashboardTracesRouteRouteChildren = {
  DashboardTracesTraceIdRoute: DashboardTracesTraceIdRoute,
  DashboardTracesIndexRoute: DashboardTracesIndexRoute,
}

const DashboardTracesRouteRouteWithChildren =
  DashboardTracesRouteRoute._addFileChildren(DashboardTracesRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAgentsRouteRoute: typeof DashboardAgentsRouteRouteWithChildren
  DashboardTracesRouteRoute: typeof DashboardTracesRouteRouteWithChildren
  DashboardOptimizationRoute: typeof DashboardOptimizationRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentsRouteRoute: DashboardAgentsRouteRouteWithChildren,
  DashboardTracesRouteRoute: DashboardTracesRouteRouteWithChildren,
  DashboardOptimizationRoute: DashboardOptimizationRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
