import { z } from "zod";

import { so } from "superobjective";

export const fetchData = so.tool({
  name: "fetch_data",
  description: so.text({
    value: "Load the customer context needed for the trace probe.",
    optimize: true,
  }),
  input: z.object({
    subject: z.string(),
    body: z.string(),
  }),
  output: z.object({
    customerId: z.string(),
    contactEmail: z.string().email(),
    orderReference: z.string(),
  }),
  async execute(input) {
    const normalized = input.subject.toLowerCase().replace(/[^a-z0-9]+/g, "-");

    return {
      customerId: `cust_${normalized || "trace-probe"}`,
      contactEmail: "customer@example.com",
      orderReference: "order_trace_probe_001",
    };
  },
});

export const checkEligibility = so.tool({
  name: "check_eligibility",
  description: so.text({
    value: "Check whether the traced case should receive automated handling.",
    optimize: true,
  }),
  input: z.object({
    queue: z.enum(["billing", "technical", "account", "trust-and-safety"]),
    severity: z.enum(["low", "medium", "high"]),
    needsHuman: z.boolean(),
  }),
  output: z.object({
    approved: z.boolean(),
    policy: z.string(),
  }),
  async execute(input) {
    return {
      approved: input.severity !== "high" && !input.needsHuman,
      policy: input.queue === "billing" ? "refund-policy-v2" : "general-support-policy-v1",
    };
  },
});

export const sendEmail = so.tool({
  name: "send_email",
  description: so.text({
    value: "Queue a customer-facing email generated by the trace probe.",
    optimize: true,
  }),
  input: z.object({
    recipient: z.string().email(),
    subject: z.string(),
    preview: z.string(),
  }),
  output: z.object({
    queued: z.boolean(),
    messageId: z.string(),
  }),
  async execute(input) {
    const normalizedRecipient = input.recipient.replace(/[^a-z0-9]+/gi, "_");

    return {
      queued: true,
      messageId: `msg_${normalizedRecipient.toLowerCase()}`,
    };
  },
});

const TraceProbeIntake = so
  .signature("trace_probe_intake")
  .withInstructions(
    "Classify the incoming support request into a concrete queue, intent, and customer tone for tracing diagnostics.",
    {
      optimize: true,
    },
  )
  .withInput("subject", z.string(), {
    description: "The support ticket subject line.",
    optimize: true,
  })
  .withInput("body", z.string(), {
    description: "The customer-written support request body.",
    optimize: true,
  })
  .withOutput("queue", z.enum(["billing", "technical", "account", "trust-and-safety"]), {
    description: "The primary internal queue that should own the case.",
    optimize: true,
  })
  .withOutput("intent", z.enum(["refund", "access", "degradation", "policy-review"]), {
    description: "The normalized user intent used for routing.",
    optimize: true,
  })
  .withOutput("customerTone", z.enum(["calm", "frustrated", "urgent"]), {
    description: "The customer tone inferred from the request.",
    optimize: true,
  })
  .build();

export const traceProbeIntake = so.predict<
  {
    subject: string;
    body: string;
  },
  {
    queue: "billing" | "technical" | "account" | "trust-and-safety";
    intent: "refund" | "access" | "degradation" | "policy-review";
    customerTone: "calm" | "frustrated" | "urgent";
  }
>(TraceProbeIntake, {
  adapter: so.adapters.xml(),
});

const TraceProbeRisk = so
  .signature("trace_probe_risk")
  .withInstructions(
    "Assess urgency, escalation pressure, and whether a human specialist should review the request.",
    {
      optimize: true,
    },
  )
  .withInput("subject", z.string(), {
    description: "The support ticket subject line.",
    optimize: true,
  })
  .withInput("body", z.string(), {
    description: "The customer-written support request body.",
    optimize: true,
  })
  .withInput("queue", z.enum(["billing", "technical", "account", "trust-and-safety"]), {
    description: "The queue predicted by the intake stage.",
    optimize: true,
  })
  .withInput("intent", z.enum(["refund", "access", "degradation", "policy-review"]), {
    description: "The intent predicted by the intake stage.",
    optimize: true,
  })
  .withInput("customerTone", z.enum(["calm", "frustrated", "urgent"]), {
    description: "The tone predicted by the intake stage.",
    optimize: true,
  })
  .withOutput("severity", z.enum(["low", "medium", "high"]), {
    description: "The urgency of the request.",
    optimize: true,
  })
  .withOutput(
    "escalationReason",
    z.enum(["none", "financial-risk", "service-risk", "policy-risk"]),
    {
      description: "Why the request should or should not be escalated.",
      optimize: true,
    },
  )
  .withOutput("needsHuman", z.boolean(), {
    description: "Whether a human specialist should take over.",
    optimize: true,
  })
  .build();

export const traceProbeRisk = so.predict<
  {
    subject: string;
    body: string;
    queue: "billing" | "technical" | "account" | "trust-and-safety";
    intent: "refund" | "access" | "degradation" | "policy-review";
    customerTone: "calm" | "frustrated" | "urgent";
  },
  {
    severity: "low" | "medium" | "high";
    escalationReason: "none" | "financial-risk" | "service-risk" | "policy-risk";
    needsHuman: boolean;
  }
>(TraceProbeRisk, {
  adapter: so.adapters.xml(),
});

const TraceProbeResolution = so
  .signature("trace_probe_resolution")
  .withInstructions(
    "Produce an operator-facing summary, next action, and customer reply draft using the earlier diagnostic stages.",
    {
      optimize: true,
    },
  )
  .withInput("subject", z.string(), {
    description: "The support ticket subject line.",
    optimize: true,
  })
  .withInput("body", z.string(), {
    description: "The customer-written support request body.",
    optimize: true,
  })
  .withInput("queue", z.enum(["billing", "technical", "account", "trust-and-safety"]), {
    description: "The queue predicted by the intake stage.",
    optimize: true,
  })
  .withInput("intent", z.enum(["refund", "access", "degradation", "policy-review"]), {
    description: "The intent predicted by the intake stage.",
    optimize: true,
  })
  .withInput("customerTone", z.enum(["calm", "frustrated", "urgent"]), {
    description: "The tone predicted by the intake stage.",
    optimize: true,
  })
  .withInput("severity", z.enum(["low", "medium", "high"]), {
    description: "The urgency predicted by the risk stage.",
    optimize: true,
  })
  .withInput(
    "escalationReason",
    z.enum(["none", "financial-risk", "service-risk", "policy-risk"]),
    {
      description: "The escalation rationale predicted by the risk stage.",
      optimize: true,
    },
  )
  .withInput("needsHuman", z.boolean(), {
    description: "Whether the risk stage recommended human review.",
    optimize: true,
  })
  .withOutput("operatorSummary", z.string(), {
    description: "A concise operator-facing summary of the case.",
    optimize: true,
  })
  .withOutput("nextAction", z.string(), {
    description: "The immediate next action for the operations team.",
    optimize: true,
  })
  .withOutput("customerReply", z.string(), {
    description: "A concise customer reply draft.",
    optimize: true,
  })
  .build();

export const traceProbeResolution = so.predict<
  {
    subject: string;
    body: string;
    queue: "billing" | "technical" | "account" | "trust-and-safety";
    intent: "refund" | "access" | "degradation" | "policy-review";
    customerTone: "calm" | "frustrated" | "urgent";
    severity: "low" | "medium" | "high";
    escalationReason: "none" | "financial-risk" | "service-risk" | "policy-risk";
    needsHuman: boolean;
  },
  {
    operatorSummary: string;
    nextAction: string;
    customerReply: string;
  }
>(TraceProbeResolution, {
  adapter: so.adapters.xml(),
});

export const traceProbeFlow = so.program({
  name: "trace_probe_flow",
  input: z.object({
    subject: z.string(),
    body: z.string(),
  }),
  output: z.object({
    intake: z.object({
      queue: z.enum(["billing", "technical", "account", "trust-and-safety"]),
      intent: z.enum(["refund", "access", "degradation", "policy-review"]),
      customerTone: z.enum(["calm", "frustrated", "urgent"]),
    }),
    risk: z.object({
      severity: z.enum(["low", "medium", "high"]),
      escalationReason: z.enum(["none", "financial-risk", "service-risk", "policy-risk"]),
      needsHuman: z.boolean(),
    }),
    resolution: z.object({
      operatorSummary: z.string(),
      nextAction: z.string(),
      customerReply: z.string(),
    }),
    toolResults: z.object({
      fetched: z.object({
        customerId: z.string(),
        contactEmail: z.string().email(),
        orderReference: z.string(),
      }),
      eligibility: z.object({
        approved: z.boolean(),
        policy: z.string(),
      }),
      email: z.object({
        queued: z.boolean(),
        messageId: z.string(),
      }),
    }),
    traceSummary: z.object({
      expectedModelCalls: z.literal(3),
      expectedToolCalls: z.literal(3),
      observedModelCalls: z.number().int().nonnegative(),
      observedToolCalls: z.number().int().nonnegative(),
      observedComponentCount: z.number().int().nonnegative(),
      note: z.string(),
    }),
  }),
  async run(ctx, input) {
    ctx.log("Trace probe started.");

    const intake = await ctx.call(traceProbeIntake, input);
    ctx.log(
      `Stage 1 complete: queue=${intake.queue}, intent=${intake.intent}, tone=${intake.customerTone}.`,
    );

    const risk = await ctx.call(traceProbeRisk, {
      ...input,
      ...intake,
    });
    ctx.log(`Stage 2 complete: severity=${risk.severity}, needsHuman=${String(risk.needsHuman)}.`);

    const fetched = await ctx.call(fetchData, input);
    ctx.log(`Fetched customer context for ${fetched.customerId}.`);

    const eligibility = await ctx.call(checkEligibility, {
      queue: intake.queue,
      severity: risk.severity,
      needsHuman: risk.needsHuman,
    });
    ctx.log(
      `Eligibility checked: approved=${String(eligibility.approved)} via ${eligibility.policy}.`,
    );

    const resolution = await ctx.call(traceProbeResolution, {
      ...input,
      ...intake,
      ...risk,
    });
    ctx.log("Stage 3 complete: resolution draft created.");

    const email = await ctx.call(sendEmail, {
      recipient: fetched.contactEmail,
      subject: input.subject,
      preview: resolution.customerReply,
    });
    ctx.log(`Queued email notification ${email.messageId}.`);

    return {
      intake,
      risk,
      resolution,
      toolResults: {
        fetched,
        eligibility,
        email,
      },
      traceSummary: {
        expectedModelCalls: 3,
        expectedToolCalls: 3,
        observedModelCalls: ctx.trace.modelCalls.length,
        observedToolCalls: ctx.trace.toolCalls.length,
        observedComponentCount: ctx.trace.components.length,
        note: "This flow intentionally chains three predict modules and three tools so the dashboard can verify mixed trace timelines.",
      },
    };
  },
});
